# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table `CRAWL_REQUESTS` (`ID` BIGINT AUTO_INCREMENT PRIMARY KEY,`ORIGIN` VARCHAR(2048) NOT NULL,`INITIAL_RECURSION_LEVEL` INTEGER NOT NULL,`INCLUDE_EXTERNALS` BOOLEAN NOT NULL);
create table `PAGE_FETCH_REQUESTS` (`ID` BIGINT AUTO_INCREMENT PRIMARY KEY,`CRAWLREQUEST_ID` BIGINT,`URL` VARCHAR(2048) NOT NULL,`STATUS_CODE` INTEGER,`CONTENT` LONGTEXT,`RECURSION_LEVEL` INTEGER NOT NULL,`INCLUDE_EXTERNALS` BOOLEAN NOT NULL);

# --- !Downs

drop table `CRAWL_REQUESTS`;
drop table `PAGE_FETCH_REQUESTS`;

